---
settings:
  name: Azure Blob storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Azure Blob Storage-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    url: "/whats-new.html"
  - title: Erste Schritte
    entries:
    - title: Anzeigen Ihrer Azure Blob-Speicherkonten
      url: "/task-view-azure-blob-storage.html"
  - title: Verwalten von Azure Blob Storage-Konten
    entries:
    - title: Neue Speicherkonten hinzufügen
      url: "/task-add-blob-storage.html"
    - title: Ändern der Speicherkontoeinstellungen
      url: "/task-change-blob-storage-settings.html"
    - title: Verwenden von NetApp -Datendiensten mit Azure Blob Storage
      url: "/task-blob-enable-data-services.html"
  - title: Wissen und Unterstützung
    entries:
    - title: Für Support registrieren
      url: "/task-support-registration.html"
    - title: Hilfe erhalten
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
