---
sidebar: sidebar 
permalink: task-blob-enable-data-services.html 
keywords: blob storage, blob working environment, azure blob storage accounts, azure blob working environment, system 
summary: Nachdem Sie Azure Blob-Speicherkonten in der NetApp Konsole ermittelt haben, können Sie NetApp Datendienste für Sicherung, Tiering und Datensynchronisierung verwenden. 
---
= Verwenden von NetApp -Datendiensten mit Azure Blob Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie Azure Blob-Speicherkonten in der NetApp Konsole ermittelt haben, können Sie NetApp Datendienste für Sicherung, Tiering und Datensynchronisierung verwenden.

* Verwenden Sie * NetApp Backup and Recovery*, um Daten von Ihren lokalen ONTAP und Cloud Volumes ONTAP -Systemen im Azure Blob-Speicher zu sichern.
+
Navigieren Sie zunächst zur Seite „Systeme“.  Ziehen Sie ein lokales ONTAP oder Cloud Volumes ONTAP -System per Drag & Drop auf Ihr Azure Blob Storage-System.

+
https://docs.netapp.com/us-en/data-services-backup-recovery/concept-ontap-backup-to-cloud.html["Erfahren Sie mehr über das Sichern von ONTAP -Daten im Azure Blob-Speicher"^] .

* Verwenden Sie * NetApp Cloud Tiering*, um inaktive Daten von lokalen ONTAP Clustern in Azure Blob Storage zu verschieben.
+
Navigieren Sie zunächst zur Seite „Systeme“.  Ziehen Sie ein lokales ONTAP -System per Drag & Drop auf Ihr Azure Blob Storage-System.

+
https://docs.netapp.com/us-en/data-services-cloud-tiering/task-tiering-onprem-azure.html["Erfahren Sie mehr über das Tiering von ONTAP -Daten in Azure Blob Storage"^] .

* Verwenden Sie * NetApp Copy and Sync*, um Daten mit oder von Azure Blob-Speicherkonten zu synchronisieren.
+
Navigieren Sie zunächst zur Seite „Systeme“.  Ziehen Sie das Quellsystem per Drag & Drop auf das Zielsystem.  Ihr Azure Blob Storage-System kann entweder die Quelle oder das Ziel sein.

+
Sie können auch Ihr Azure Blob Storage-System auswählen und dann im Bereich „Dienste“ auf „Kopieren und Synchronisieren“ klicken, um Daten mit oder von Azure Blob Storage-Konten zu synchronisieren.

+
https://docs.netapp.com/us-en/data-services-copy-sync/concept-cloud-sync.html["Erfahren Sie mehr über Kopieren und Synchronisieren"^] .


